# Generated by Django 5.2.10 on 2026-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=60, verbose_name='Contraseña')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre Usuario')),
                ('email', models.CharField(max_length=70, verbose_name='Email')),
                ('tel', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Balance')),
                ('steam_api_token', models.CharField(help_text='Steam Web API Key', max_length=255, unique=True)),
            ],
        ),
    ]
