# Generated by Django 5.2.10 on 2026-05-08 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_activo_user_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario (legado)', 'verbose_name_plural': 'Usuarios (legado)'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Balance')),
                ('steam_api_token', models.CharField(blank=True, default='', help_text='Steam Web API Key', max_length=255)),
                ('tel', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('avatar_url', models.URLField(blank=True, default='', help_text='URL de imagen de perfil (Steam o Google)', verbose_name='Avatar URL')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
