# Generated by Django 5.2.10 on 2026-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('desgaste', models.DecimalField(decimal_places=12, max_digits=13, verbose_name='float')),
                ('stattrack', models.BooleanField(verbose_name='stattrack')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('categoria', models.CharField(choices=[('PISTOL', 'Pistola'), ('SMG', 'Subfusil'), ('RIFLE', 'Rifle'), ('SNIPER', 'Francotirador'), ('SHOTGUN', 'Escopeta'), ('MACHINE_GUN', 'Ametralladora'), ('KNIFE', 'Cuchillo'), ('GLOVES', 'Guantes')], max_length=30)),
                ('rareza', models.CharField(choices=[('CONSUMER', 'Consumer Grade'), ('INDUSTRIAL', 'Industrial Grade'), ('MIL_SPEC', 'Mil-Spec'), ('RESTRICTED', 'Restricted'), ('CLASSIFIED', 'Classified'), ('COVERT', 'Covert'), ('CONTRABAND', 'Contraband')], max_length=30)),
            ],
        ),
    ]
