# Generated by Django 5.2.10 on 2026-05-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duracion_horas',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 hora'), (6, '6 horas'), (12, '12 horas'), (24, '24 horas'), (48, '48 horas'), (72, '72 horas')], default=24, verbose_name='Duración en horas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
    ]
