# Generated by Django 5.2.10 on 2026-05-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('id_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='skins.skin')),
            ],
        ),
    ]
